### ISSUE TITLE
No polytools library and can't build the system

### ISSUE THREAD

**Issue by lonhuen** [MarbleHE/ringSNARK#2]
Hi,

I came across your paper on arxiv and I'm interested in running some experiments (benchmark proof generation for FHE multiplications) myself. However, I just noticed that `polytools` is not open-sourced and I can't build the system.

Are there any possible ways for me to benchmark proof generation for HE multiplications myself with your code?

Thanks!

**Comment by cknabs** [comment]
Hi @lonhuen, thanks for your interest in our code! 
Indeed, `polytools` is not (yet) open-source, so you will not be able to run benchmarks by yourself at the moment.   

We're actively trying to mitigate this limitation, and we believe that `polytools` will be made open-source sometime this year, but there is some non-trivial administrative work required. As a temporary fix, I'm working on a patch that will side-step `polytools` and call SEAL directly, so that anyone can use `ringSNARK` freely. We're also considering supporting OpenFHE as an additional backend as well, but implementing this will take some time. 

Is there anything specific you wanted to evaluate? The `Toy` example in [the paper](https://arxiv.org/pdf/2301.07041.pdf) benchmarks one ciphertext-ciphertext multiplication, which might be exactly what you're looking for.
